apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-films
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-films
  template:
    metadata:
      labels:
        app: cinema-films
    spec:
      containers:
        -
          image: myfirstmolly/filmservice
          name: cinema-films
          ports:
            -
              containerPort: 8081
              name: cinema-films
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.0.101:5432/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"